FROM golang:1.24-alpine AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /out/cdc-transformer ./apps/cdc-transformer/cmd

FROM alpine:3.19
WORKDIR /app
COPY --from=build /out/cdc-transformer /app/cdc-transformer

CMD ["/app/cdc-transformer"]