apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: grainguard
  namespace: argocd
spec:
  description: GrainGuard platform project
  sourceRepos:
    - https://github.com/pahuldeepp/GrainGuard-.git
  destinations:
    - namespace: grainguard-dev
      server: https://kubernetes.default.svc
    - namespace: grainguard-prod
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
