apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grainguard-secrets
  namespace: grainguard-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: grainguard-secret-store
    kind: SecretStore
  target:
    name: grainguard-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grainguard/dev
