apiVersion: v1
kind: ServiceAccount
metadata:
  name: grainguard-secrets-sa
  namespace: grainguard-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/grainguard-external-secrets-role
