// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: libs/events/proto/event_envelope.proto

package eventspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaVersion    int32                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAtUnixMs int64                  `protobuf:"varint,4,opt,name=occurred_at_unix_ms,json=occurredAtUnixMs,proto3" json:"occurred_at_unix_ms,omitempty"`
	TenantId         string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AggregateId      string                 `protobuf:"bytes,6,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EventEnvelope_TelemetryRecordedV1
	//	*EventEnvelope_DeviceCreatedV1
	Payload       isEventEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_libs_events_proto_event_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventEnvelope) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventEnvelope) GetOccurredAtUnixMs() int64 {
	if x != nil {
		return x.OccurredAtUnixMs
	}
	return 0
}

func (x *EventEnvelope) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EventEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *EventEnvelope) GetPayload() isEventEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetTelemetryRecordedV1() *TelemetryRecordedV1 {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_TelemetryRecordedV1); ok {
			return x.TelemetryRecordedV1
		}
	}
	return nil
}

func (x *EventEnvelope) GetDeviceCreatedV1() *DeviceCreatedV1 {
	if x != nil {
		if x, ok := x.Payload.(*EventEnvelope_DeviceCreatedV1); ok {
			return x.DeviceCreatedV1
		}
	}
	return nil
}

type isEventEnvelope_Payload interface {
	isEventEnvelope_Payload()
}

type EventEnvelope_TelemetryRecordedV1 struct {
	TelemetryRecordedV1 *TelemetryRecordedV1 `protobuf:"bytes,100,opt,name=telemetry_recorded_v1,json=telemetryRecordedV1,proto3,oneof"`
}

type EventEnvelope_DeviceCreatedV1 struct {
	DeviceCreatedV1 *DeviceCreatedV1 `protobuf:"bytes,101,opt,name=device_created_v1,json=deviceCreatedV1,proto3,oneof"`
}

func (*EventEnvelope_TelemetryRecordedV1) isEventEnvelope_Payload() {}

func (*EventEnvelope_DeviceCreatedV1) isEventEnvelope_Payload() {}

type TelemetryRecordedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Temperature   float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,4,opt,name=humidity,proto3" json:"humidity,omitempty"`
	RecordedAt    string                 `protobuf:"bytes,5,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRecordedV1) Reset() {
	*x = TelemetryRecordedV1{}
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecordedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecordedV1) ProtoMessage() {}

func (x *TelemetryRecordedV1) ProtoReflect() protoreflect.Message {
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecordedV1.ProtoReflect.Descriptor instead.
func (*TelemetryRecordedV1) Descriptor() ([]byte, []int) {
	return file_libs_events_proto_event_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryRecordedV1) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TelemetryRecordedV1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryRecordedV1) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *TelemetryRecordedV1) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *TelemetryRecordedV1) GetRecordedAt() string {
	if x != nil {
		return x.RecordedAt
	}
	return ""
}

type DeviceCreatedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Serial        string                 `protobuf:"bytes,3,opt,name=serial,proto3" json:"serial,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCreatedV1) Reset() {
	*x = DeviceCreatedV1{}
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCreatedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreatedV1) ProtoMessage() {}

func (x *DeviceCreatedV1) ProtoReflect() protoreflect.Message {
	mi := &file_libs_events_proto_event_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreatedV1.ProtoReflect.Descriptor instead.
func (*DeviceCreatedV1) Descriptor() ([]byte, []int) {
	return file_libs_events_proto_event_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceCreatedV1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceCreatedV1) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeviceCreatedV1) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *DeviceCreatedV1) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_libs_events_proto_event_envelope_proto protoreflect.FileDescriptor

const file_libs_events_proto_event_envelope_proto_rawDesc = "" +
	"\n" +
	"&libs/events/proto/event_envelope.proto\x12\x14grainguard.events.v1\"\xa0\x03\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\x12-\n" +
	"\x13occurred_at_unix_ms\x18\x04 \x01(\x03R\x10occurredAtUnixMs\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12!\n" +
	"\faggregate_id\x18\x06 \x01(\tR\vaggregateId\x12_\n" +
	"\x15telemetry_recorded_v1\x18d \x01(\v2).grainguard.events.v1.TelemetryRecordedV1H\x00R\x13telemetryRecordedV1\x12S\n" +
	"\x11device_created_v1\x18e \x01(\v2%.grainguard.events.v1.DeviceCreatedV1H\x00R\x0fdeviceCreatedV1B\t\n" +
	"\apayload\"\xa1\x01\n" +
	"\x13TelemetryRecordedV1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x01R\bhumidity\x12\x1f\n" +
	"\vrecorded_at\x18\x05 \x01(\tR\n" +
	"recordedAt\"\x82\x01\n" +
	"\x0fDeviceCreatedV1\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06serial\x18\x03 \x01(\tR\x06serial\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAtB;Z9github.com/pahuldeepp/grainguard/libs/events/gen;eventspbb\x06proto3"

var (
	file_libs_events_proto_event_envelope_proto_rawDescOnce sync.Once
	file_libs_events_proto_event_envelope_proto_rawDescData []byte
)

func file_libs_events_proto_event_envelope_proto_rawDescGZIP() []byte {
	file_libs_events_proto_event_envelope_proto_rawDescOnce.Do(func() {
		file_libs_events_proto_event_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_events_proto_event_envelope_proto_rawDesc), len(file_libs_events_proto_event_envelope_proto_rawDesc)))
	})
	return file_libs_events_proto_event_envelope_proto_rawDescData
}

var file_libs_events_proto_event_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libs_events_proto_event_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil),       // 0: grainguard.events.v1.EventEnvelope
	(*TelemetryRecordedV1)(nil), // 1: grainguard.events.v1.TelemetryRecordedV1
	(*DeviceCreatedV1)(nil),     // 2: grainguard.events.v1.DeviceCreatedV1
}
var file_libs_events_proto_event_envelope_proto_depIdxs = []int32{
	1, // 0: grainguard.events.v1.EventEnvelope.telemetry_recorded_v1:type_name -> grainguard.events.v1.TelemetryRecordedV1
	2, // 1: grainguard.events.v1.EventEnvelope.device_created_v1:type_name -> grainguard.events.v1.DeviceCreatedV1
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_libs_events_proto_event_envelope_proto_init() }
func file_libs_events_proto_event_envelope_proto_init() {
	if File_libs_events_proto_event_envelope_proto != nil {
		return
	}
	file_libs_events_proto_event_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*EventEnvelope_TelemetryRecordedV1)(nil),
		(*EventEnvelope_DeviceCreatedV1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_events_proto_event_envelope_proto_rawDesc), len(file_libs_events_proto_event_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_libs_events_proto_event_envelope_proto_goTypes,
		DependencyIndexes: file_libs_events_proto_event_envelope_proto_depIdxs,
		MessageInfos:      file_libs_events_proto_event_envelope_proto_msgTypes,
	}.Build()
	File_libs_events_proto_event_envelope_proto = out.File
	file_libs_events_proto_event_envelope_proto_goTypes = nil
	file_libs_events_proto_event_envelope_proto_depIdxs = nil
}

